FROM cybersecnatlab/socaz:ubuntu-noble AS socaz

FROM ubuntu:24.04@sha256:d1e2e92c075e5ca139d51a140fff46f84315c0fdce203eab2807c7e495eff4f9

COPY --from=socaz /usr/local/bin/socaz /usr/local/bin/socaz

RUN apt-get clean
RUN apt-get update && apt-get install -y \
    socat
RUN rm -rf /var/lib/apt/lists/*

RUN useradd userchall
WORKDIR /challenge

COPY --chown=root:userchall --chmod=050 ./binary .
COPY --chown=root:userchall --chmod=040 ./flag.txt .

USER userchall

EXPOSE 1089
ENTRYPOINT ["socaz", "--timeout", "60", "--bind", "1089", "--cmd", "timeout 60s /challenge/binary"]
