import random, os, tqdm

RC = [
    0x0000000000000073, 0x0000000000000072, 0x0000000000000064, 0x000000000000006e, 
    0x000000000000006c, 0x0000000000000065, 0x000000000000006e, 0x0000000000000032, 
    0x0000000000000030, 0x0000000000000032, 0x0000000000000036, 0x0000000000000021
]
iv = 0x7372646e6c656e21
rrot = lambda x, n: (x >> n) | (x << (64 - n)) & 0xffffffffffffffff


def permutation(state: tuple[int], r: int) -> tuple[int]:
    global RC
    x0, x1, x2, x3, x4 = state
    # Constant-Addition Layer
    # x2 ^= RC[r]  # removed for easier testing
    # Substitution Layer
    x0 ^= x4
    x2 ^= x1
    x4 ^= x3
    t0 = (x0 ^ 0xffffffffffffffff) & x1
    t1 = (x1 ^ 0xffffffffffffffff) & x2
    t2 = (x2 ^ 0xffffffffffffffff) & x3
    t3 = (x3 ^ 0xffffffffffffffff) & x4
    t4 = (x4 ^ 0xffffffffffffffff) & x0
    x0 ^= t1
    x1 ^= t2
    x2 ^= t3
    x3 ^= t4
    x4 ^= t0
    x1 ^= x0
    x3 ^= x2
    x0 ^= x4
    x2 ^= 0xffffffffffffffff
    # Linear Diffusion Layer
    x0 ^= rrot(x0, 19) ^ rrot(x0, 28)
    x1 ^= rrot(x1, 61) ^ rrot(x1, 39)
    x2 ^= rrot(x2, 1) ^ rrot(x2, 6)
    x3 ^= rrot(x3, 10) ^ rrot(x3, 17)
    x4 ^= rrot(x4, 7) ^ rrot(x4, 41)
    return (x0, x1, x2, x3, x4)


def ascon(key: int, nonce: int, nrounds: int = 4) -> int:
    state = (
        iv, 
        key >> 64, 
        key & 0xffffffffffffffff, 
        nonce >> 64, 
        nonce & 0xffffffffffffffff
    )
    for r in range(nrounds):
        state = permutation(state, r)
    x0, x1, x2, x3, x4 = state
    return x0 << 64 | x1


seed = os.urandom(32)
random.seed(seed)

key = random.getrandbits(128)

# DL distinguishers obtained from https://github.com/hadipourh/DL/tree/main
# by executing the Ascon attack with RU = 1, RM = 3 and RL = 0, i.e. the cmdline:
# python3 attack.py -RU 1 -RM 3 -RL 0 -np 12
# By modifying attack.mzn file with appropriate constraints for Ascon AEAD
# and changing the target output difference after the first sbox layer
# we obtain different distinguishers with different biases.
# Beware that the tool is probabilistic and may not always return the same
# distinguishers, although they should be equivalent from the attack perspective.
# Low hamming weight differences are generally more useful for attacks, 
# for that reason we have selected the distinguishers starting from the one
# with the lowest possible hamming weight.

# Generated by requiring that the difference after the first sbox layer is
# (1, 0, 0, 0, 0)
# for k=00 bias is around 0.5, while for others it is around 0.0
diff0, diff1 = 0x8000000000000000, 0x8000000000000000
mask0, mask1 = 0x2db36f2549927b69, 0x92b573be8bc1c7b3

# Generated by requiring that the difference after the first sbox layer is
# (0, 0, 0, 0, 1)
# for k=00 and k=11 bias is around 0.5
# for k=01 and k=10 bias is around -0.25
diff0, diff1 = 0x8000000000000000, 0x8000000000000000
mask0, mask1 = 0x96da496ddb493244, 0x0000000000000000

# Generated to obtain a distinguisher for the last two possible key values
# i.e. k=01 and k=10 (I just tried some of them and this one had a good bias)
# for k=00 and k=01 bias is around 0.37
# for k=10 and k=11 bias is around 0.58
diff0, diff1 = 0x8000000000000000, 0x8000000000000000
mask0, mask1 = 0x496da496ddb49324, 0xd37110f752d23e65

mask0, mask1 = 0x96da496ddb493244, 0x0000000000000000


k_to_biases = {
    "k=00": {
        "iv=0": [],
        "iv=1": [],
    },
    "k=01": {
        "iv=0": [],
        "iv=1": [],
    },
    "k=10": {
        "iv=0": [],
        "iv=1": [],
    },
    "k=11": {
        "iv=0": [],
        "iv=1": [],
    },
}

nqueries = 1 << 12
for idx in tqdm.trange(64):
    diff = rrot(diff0, idx) << 64 | rrot(diff1, idx)
    mask = rrot(mask0, idx) << 64 | rrot(mask1, idx)
    cnt = 0
    for _ in range(nqueries):
        nonce = random.getrandbits(128)
        out1 = ascon(key, nonce)
        out2 = ascon(key, nonce ^ diff)
        if ((out1 ^ out2) & mask).bit_count() & 1 == 0:
            cnt += 1
        else:
            cnt -= 1
    k = key >> (126 - idx) & 0b10 | key >> (63 - idx) & 0b01
    k_to_biases[f"k={k:02b}"][f"iv={iv >> (63 - idx) & 1}"].append(cnt / nqueries)

for k, iv_biases in k_to_biases.items():
    for iv, biases in iv_biases.items():
        avg_bias = sum(biases) / len(biases) if biases else 0.0
        max_bias = max(biases, default=0.0)
        min_bias = min(biases, default=0.0)
        print(f"{k}, {iv}: {avg_bias:.6f} (max bias: {max_bias:.6f}, min bias: {min_bias:.6f})")
