server {
    listen 80;
		absolute_redirect off;


    location /report {
        proxy_pass http://afterimage-bot:3000/;
        proxy_set_header Host $host;
				proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
				proxy_read_timeout 150s;
        proxy_send_timeout 150s;
        proxy_connect_timeout 150s;
    }

    location / {
        proxy_pass http://afterimage-web:80/;
        proxy_set_header Host $host;
				proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    }
}
