FROM cybersecnatlab/socaz:ubuntu-noble AS socaz-state

FROM ubuntu:25.10@sha256:4a9232cc47bf99defcc8860ef6222c99773330367fcecbf21ba2edb0b810a31e

RUN apt-get clean
RUN apt-get update && apt-get install -y make gcc build-essential
RUN rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./linx.c .
COPY ./Makefile .

ENTRYPOINT ["make"]

