FROM ubuntu:24.04@sha256:d1e2e92c075e5ca139d51a140fff46f84315c0fdce203eab2807c7e495eff4f9

RUN apt-get clean
RUN apt-get update && apt-get install -y \
    build-essential=12.10ubuntu1 \
    libcapstone-dev=4.0.2-5.1build1
